// Suggested club categories; clubs can also type their own
export const clubCategories = [
  "Academic",
  "Professional",
  "Technology",
  "Engineering",
  "Science",
  "Business",
  "Arts",
  "Music",
  "Performing Arts",
  "Media & Publications",
  "Cultural",
  "Religious & Spiritual",
  "Community Service",
  "Advocacy & Social Justice",
  "Political",
  "Health & Wellness",
  "Sports & Recreation",
  "Gaming & Esports",
  "Greek Life",
  "Honor Society",
  "Student Government",
  "Hobbies & Special Interest",
  "Other",
] as const;
