export const majorOptions = [
	"Computer Science",
	"Accounting",
	"Accounting Technician",
	"Actuarial Science",
	"Advertising",
	"Aerospace/Aeronautical Engineering",
	"African American/Black Studies",
	"Agricultural Business & Management",
	"Agricultural Economics",
	"Agricultural Mechanization",
	"Agricultural Production",
	"Agricultural/Bioengineering",
	"American/English Literature",
	"Animal Sciences",
	"Animation & Special Effects",
	"Anthropology",
	"Applied Mathematics",
	"Archaeology",
	"Architectural Engineering",
	"Architecture",
	"Art History, Criticism & Conservation",
	"Art, General",
	"Artificial Intelligence",
	"Asian Studies",
	"Astronomy",
	"Athletic Training",
	"Atmospheric Sciences & Meteorology",
	"Aviation/Airline Pilot",
	"Banking & Financial Support Services",
	"Biochemistry & Biophysics",
	"Biology, General",
	"Biomedical Engineering",
	"Botany/Plant Biology",
	"Broadcasting (Radio & Television)",
	"Business Administration & Management, General",
	"Business/Management Quantitative Methods, General",
	"Business/Managerial Economics",
	"Cell/Cellular Biology",
	"Chemical Engineering",
	"Chemistry",
	"Child Development",
	"Chinese Language & Literature",
	"Cinematography/Film/Video Production",
	"Civil Engineering",
	"Classical/Ancient Languages & Literatures",
	"Communications, General",
	"Comparative Literature",
	"Computer & Information Sciences, General",
	"Computer Engineering",
	"Computer Networking/Telecommunications",
	"Computer Software & Media Applications",
	"Computer System Administration",
	"Construction Engineering/Management",
	"Creative Writing",
	"Criminal Justice",
	"Criminology",
	"Culinary Arts",
	"Cyber Security",
	"Dance",
	"Data Management Technology",
	"Data Science",
	"Dental Assisting",
	"Dental Hygiene",
	"Dentistry (Pre-Dentistry)",
	"Design & Visual Communications, General",
	"Digital Media",
	"Early Childhood Education",
	"Ecology",
	"Economics",
	"Education, General",
	"Educational Leadership & Administration",
	"Electrical Engineering",
	"Elementary Education",
	"Emergency Medical Technology (EMT/Paramedic)",
	"Engineering (Pre-Engineering), General",
	"Engineering Technology",
	"English as a Second Language (ESL/TESOL)",
	"English Language & Literature, General",
	"Entrepreneurship",
	"Environmental Engineering",
	"Environmental Science",
	"Environmental Studies",
	"Exercise Science & Kinesiology",
	"Fashion Design",
	"Fashion Merchandising",
	"Film Studies",
	"Finance, General",
	"Financial Planning & Services",
	"Fine/Studio Arts",
	"Fire Science & Firefighting",
	"Food Sciences & Technology",
	"Foreign Languages/Literatures, General",
	"Forensic Science",
	"Forestry",
	"French Language & Literature",
	"Game Design & Development",
	"Gender & Women's Studies",
	"Genetics",
	"Geography",
	"Geological & Earth Sciences",
	"German Language & Literature",
	"Graphic Design",
	"Health Sciences, General",
	"Health Services Administration,General",
	"History",
	"Horticulture",
	"Hospitality & Hotel Management",
	"Human Development & Family Studies",
	"Human Resources Development/Training",
	"Human Resources Management",
	"Industrial Design",
	"Industrial Engineering",
	"Information Science",
	"Information Technology And Systems",
	"Insurance & Risk Management",
	"Interior Design",
	"International Business Management",
	"International Relations & Affairs",
	"Investments & Securities",
	"Japanese Language & Literature",
	"Journalism",
	"Labor/Industrial Relations",
	"Landscape Architecture",
	"Latin American Studies",
	"Law (Pre-Law)",
	"Legal Administrative Assisting/Secretarial",
	"Legal Studies, General",
	"Liberal Arts & Sciences, General Studies",
	"Library Science",
	"Linguistics",
	"Logistics & Materials Management",
	"Management Information Systems",
	"Marine/Aquatic Biology",
	"Marketing Management & Research",
	"Mass Communication/Media Studies",
	"Materials Science & Engineering",
	"Mathematics Education",
	"Mathematics, General",
	"Mechanical Engineering",
	"Mechatronics & Robotics Engineering",
	"Medical Assisting",
	"Medical Laboratory Science",
	"Medical Office/Secretarial",
	"Medical Records",
	"Medical/Clinical Assisting, General",
	"Medicine (Pre-Medicine)",
	"Microbiology & Immunology",
	"Middle Eastern Studies",
	"Military Science",
	"Mining Engineering",
	"Music Education",
	"Music Performance",
	"Music, General",
	"Music, Theory & Composition",
	"Native American Studies",
	"Natural Resources Conservation, General",
	"Natural Resources Management",
	"Neuroscience",
	"Nonprofit Management",
	"Nuclear Engineering",
	"Nursing (RN/BSN)",
	"Nutrition & Dietetics",
	"Occupational Therapy Assisting",
	"Operations Management",
	"Paralegal Studies",
	"Petroleum Engineering",
	"Pharmacy (Pre-Pharmacy)",
	"Philosophy",
	"Photography",
	"Physical Education & Coaching",
	"Physical Sciences, General",
	"Physical Therapy Assisting",
	"Physician Assistant (Pre-PA)",
	"Physics",
	"Political Science & Government",
	"Project Management",
	"Psychology, Clinical & Counseling",
	"Psychology, General",
	"Public Administration",
	"Public Health",
	"Public Policy",
	"Public Relations",
	"Public Speaking",
	"Radiologic Technology",
	"Real Estate",
	"Religious Studies",
	"Respiratory Therapy",
	"Sales, Merchandising, & Marketing, General",
	"Science Education",
	"Secondary Education",
	"Secretarial Studies & Office Administration",
	"Small Business Management/Operations",
	"Social Sciences, General",
	"Social Work",
	"Sociology",
	"Software Engineering",
	"Spanish Language & Literature",
	"Special Education",
	"Speech-Language Pathology",
	"Sport & Recreation Management",
	"Statistics",
	"Supply Chain Management",
	"Theatre/Drama",
	"Theology",
	"Tourism & Travel Management",
	"Urban Planning",
	"Urban Studies/Urban Affairs",
	"Veterinary Medicine (Pre-Veterinary)",
	"Veterinary Technology",
	"Webpage Design",
	"Wildlife & Wildlife Management",
	"Zoology",
	"Undecided / Undeclared",
	"Other",
] as const;
