// Social platforms; the database stores the code (e.g. "instagram")
export const socialPlatform = [
	{ name: "Instagram", code: "instagram" },
	{ name: "TikTok", code: "tiktok" },
	{ name: "X", code: "x" },
	{ name: "Facebook", code: "facebook" },
	{ name: "LinkedIn", code: "linkedin" },
	{ name: "YouTube", code: "youtube" },
	{ name: "Discord", code: "discord" },
	{ name: "GitHub", code: "github" },
	{ name: "Snapchat", code: "snapchat" },
	{ name: "Threads", code: "threads" },
	{ name: "Bluesky", code: "bluesky" },
	{ name: "Reddit", code: "reddit" },
	{ name: "Twitch", code: "twitch" },
	{ name: "Pinterest", code: "pinterest" },
	{ name: "Slack", code: "slack" },
	{ name: "GroupMe", code: "groupme" },
	{ name: "WhatsApp", code: "whatsapp" },
	{ name: "Telegram", code: "telegram" },
	{ name: "Devpost", code: "devpost" },
	{ name: "Medium", code: "medium" },
	{ name: "Substack", code: "substack" },
	{ name: "Linktree", code: "linktree" },
	{ name: "Website", code: "website" },
	{ name: "Other", code: "other" },
] as const;
